### ISSUE TITLE
einzugsDatum allow None

### ISSUE THREAD

**Issue by f1shl** [sscholz93/pynami#3]
Servus,
bei Rechnungen (besonders ältere) kann es öfters vorkommen, dass das EinzugsDatum nicht ausgefüllt ist. Ich schlage daher vor, dass man in grpadmin.py, Zeile 176 folgendes ändert:
**einzugsDatum = fields.Date(allow_none=True)
""":class:`~datetime.datetime`: Date of money collection"""** 

Ansonsten kommt immer die Exception: _marshmallow.exceptions.ValidationError: {'einzugsDatum': ['Field may not be null.']}_

**Comment by sscholz93** [comment]
Danke für den Hinweis, habe ich angepasst
